### ISSUE TITLE
Store meta data into MongoDB

### ISSUE THREAD

**Issue by don-han** [BIDS-projects/web-scraper#28]
- [ ] time started/ended
- [ ] total number of webpages crawled
- [ ] number of new webpages stored
